//
//  AddComputerView.swift
//  WOLMonitoring
//
//  Created by Keith Beavers on 9/25/25.
//

// Generated by Google Gemini 2.5 Pro on Thu Sep 25th, 2025 @ 0117

import SwiftUI

struct AddComputerView: View {
    @ObservedObject var computerManager: ComputerManager
    @Environment(\.dismiss) var dismiss

    @State private var name: String = ""
    
    private var isFormValid: Bool {
        // Form is valid if name is not empty.
        return !name.trimmingCharacters(in: .whitespaces).isEmpty
    }

    var body: some View {
        NavigationStack {
            Form {
                TextField("Computer Name", text: $name)
            }
            .navigationTitle("New Computer")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") {
                        dismiss()
                    }
                }
                ToolbarItem(placement: .confirmationAction) {
                    Button("Save") {
                        // Only save if the form is valid
                        if isFormValid {
                            let newComputer = Computer(name: name, components: [])
                            computerManager.addComputer(newComputer)
                            dismiss()
                        }
                    }
                    .disabled(!isFormValid) // Disable Save button if form is not valid
                }
            }
        }
    }
}
