//
//  AddComputerView.swift
//  WOLMonitoring
//
//  Created by Keith Beavers on 9/25/25.
//

// Generated by Google Gemini 2.5 Pro on Thu Sep 25th, 2025 @ 0117

import SwiftUI

struct AddComputerView: View {
    @ObservedObject var computerManager: ComputerManager
    @Environment(\.dismiss) var dismiss

    @State private var name: String = ""
    @State private var macAddress: String = ""
    
    private var isFormValid: Bool {
        !name.trimmingCharacters(in: .whitespaces).isEmpty &&
        !macAddress.trimmingCharacters(in: .whitespaces).isEmpty
    }

    var body: some View {
        NavigationStack {
            Form {
                TextField("Computer Name", text: $name)
                TextField("MAC Address", text: $macAddress)
                    .autocorrectionDisabled()
                    .textInputAutocapitalization(.never)
            }
            .navigationTitle("New Computer")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") {
                        dismiss()
                    }
                }
                ToolbarItem(placement: .confirmationAction) {
                    Button("Save") {
                        let newComputer = Computer(name: name, macAddress: macAddress)
                        computerManager.addComputer(newComputer)
                        dismiss()
                    }
                    .disabled(!isFormValid)
                }
            }
        }
    }
}
