//
//  EditComputerView.swift
//  WOLMonitoring
//
//  Created by Keith Beavers on 9/25/25.
//

// Generated by Google Gemini 2.5 Pro/Flash on Thu Sep 25th, 2025 @ 1003

import SwiftUI

struct EditComputerView: View {
    @Binding var computer: Computer
    @Environment(\.dismiss) var dismiss

    @State private var computerName: String
    @State private var macAddress: String
    
    @State private var macAddressError: String? // New state for MAC address error message

    private var isFormValid: Bool {
        // Form is valid if computerName is not empty, macAddress is not empty (after trimming),
        // and there is no MAC address validation error.
        return !computerName.trimmingCharacters(in: .whitespaces).isEmpty &&
               !macAddress.trimmingCharacters(in: .whitespaces).isEmpty &&
               macAddressError == nil
    }

    init(computer: Binding<Computer>) {
        _computer = computer
        _computerName = State(initialValue: computer.wrappedValue.name ?? "")
        _macAddress = State(initialValue: computer.wrappedValue.macAddress ?? "")

        // Perform initial validation for MAC address
        let initialMac = computer.wrappedValue.macAddress ?? ""
        if initialMac.trimmingCharacters(in: .whitespaces).isEmpty {
            _macAddressError = State(initialValue: "MAC Address cannot be empty.")
        } else if !isValidMACAddress(initialMac) {
            _macAddressError = State(initialValue: "Invalid MAC Address format. E.g., 00:11:22:33:44:55")
        } else {
            _macAddressError = State(initialValue: nil)
        }
    }

    var body: some View {
        NavigationStack {
            Form {
                Section("Computer Details") {
                    TextField("Computer Name", text: $computerName)
                    
                    VStack(alignment: .leading) { // Wrap TextField and error message in a VStack
                        TextField("MAC Address", text: $macAddress)
                            .autocorrectionDisabled()
                            .textInputAutocapitalization(.never)
                            .onChange(of: macAddress) {
                                // Validate MAC address input in real-time
                                validateMacAddressInput(macAddress)
                            }
                        
                        if let error = macAddressError {
                            Text(error)
                                .font(.caption)
                                .foregroundStyle(.red)
                        }
                    }
                }
                
                Section("Components") {
                    ForEach($computer.components) { $component in
                        ComponentEditView(component: $component)
                    }
                    .onDelete(perform: deleteComponent)
                }
            }
            .navigationTitle("Edit Computer")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel", role: .cancel) {
                        dismiss()
                    }
                }
                ToolbarItem(placement: .topBarTrailing) {
                    EditButton()
                }
                ToolbarItem(placement: .topBarTrailing) {
                    Menu {
                        Button("Add IP Address") {
                            // When a sensor exists without an IP, adding one will automatically
                            // trigger the ComputerManager to start polling.
                            let newIP = IPData()
                            computer.components.append(.ipAddress(newIP))
                        }
                        Button("Add Sensor") {
                            // Default to CPU Temp with ºC units
                            let newSensor = SensorData(type: "CPU Temp", unit: "ºC")
                            computer.components.append(.sensor(newSensor))
                        }
                    } label: {
                        Label("Add Component", systemImage: "plus")
                    }
                }
                ToolbarItem(placement: .confirmationAction) {
                    Button("Save") {
                        // Perform a final validation check before saving
                        validateMacAddressInput(macAddress)
                        
                        // Only save if the form is valid
                        if isFormValid {
                            computer.name = computerName
                            computer.macAddress = macAddress
                            
                            // If a CPU Temp sensor exists but no IP, add a default one.
                            let hasCPUTempSensor = computer.components.contains {
                                if case .sensor(let sData) = $0, sData.type == "CPU Temp" { return true } else { return false }
                            }
                            let hasIPAddress = computer.components.contains {
                                if case .ipAddress = $0 { return true } else { return false }
                            }
                            if hasCPUTempSensor && !hasIPAddress {
                                computer.components.append(.ipAddress(IPData()))
                            }
                            
                            dismiss()
                        }
                    }
                    .disabled(!isFormValid) // Disable Save button if form is not valid
                }
            }
        }
    }
    
    private func deleteComponent(at offsets: IndexSet) {
        computer.components.remove(atOffsets: offsets)
    }
    
    // MARK: - MAC Address Validation
    
    /// Validates the given MAC address input and updates the `macAddressError` state.
    private func validateMacAddressInput(_ input: String) {
        let trimmedInput = input.trimmingCharacters(in: .whitespaces)
        
        if trimmedInput.isEmpty {
            macAddressError = "MAC Address cannot be empty."
        } else if !isValidMACAddress(trimmedInput) {
            macAddressError = "Invalid MAC Address format. E.g., 00:11:22:33:44:55"
        } else {
            macAddressError = nil // MAC address is valid
        }
    }
    
    /// Checks if a given string represents a valid MAC address format.
    /// It allows for common separators like colons, hyphens, and spaces, or no separators.
    private func isValidMACAddress(_ mac: String) -> Bool {
        // Remove common separators (colon, hyphen, space) for validation
        let cleanMAC = mac.replacingOccurrences(of: "[: -]", with: "", options: .regularExpression)
        
        // A valid MAC address must consist of exactly 12 hexadecimal characters
        guard cleanMAC.count == 12 else {
            return false
        }
        
        // Check if all characters in the cleaned string are hexadecimal digits
        let hexCharset = CharacterSet(charactersIn: "01256789abcdefABCDEF")
        return cleanMAC.rangeOfCharacter(from: hexCharset.inverted) == nil
    }
}

fileprivate struct ComponentEditView: View {
    @Binding var component: Component
    
    var body: some View {
        // Switch on the wrappedValue of the binding, then use the new sub-bindings.
        switch component {
        case .ipAddress:
            if let ipDataBinding = $component.ipAddress {
                VStack(alignment: .leading) {
                    Text("IP Address")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                    TextField("Address", text: ipDataBinding.address)
                        .autocorrectionDisabled()
                        .textInputAutocapitalization(.never)
                }
            }
        case .sensor:
            if let sensorDataBinding = $component.sensor {
                VStack(alignment: .leading) {
                    Text("Sensor")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                    TextField("Sensor Name", text: sensorDataBinding.name)

                    // New: Picker for sensor type
                    Picker("Sensor Type", selection: sensorDataBinding.type) {
                        Text("CPU Temp").tag("CPU Temp")
                        // Add other sensor types here as they are introduced
                    }
                    .pickerStyle(.segmented) // Or .menu
                    .onChange(of: sensorDataBinding.type.wrappedValue) { newType in
                        // When type changes, update unit if it's "CPU Temp"
                        if newType == "CPU Temp" {
                            sensorDataBinding.unit.wrappedValue = "ºC"
                        }
                    }

                    HStack {
                        // Display the polled value, but don't allow direct editing for CPU Temp
                        Text(sensorDataBinding.wrappedValue.type == "CPU Temp" ? "\(String(format: "%.1f", sensorDataBinding.wrappedValue.value))" : "")
                            .frame(maxWidth: .infinity, alignment: .leading)
                        
                        if sensorDataBinding.wrappedValue.type != "CPU Temp" {
                            TextField("Value", value: sensorDataBinding.value, format: .number)
                                .keyboardType(.decimalPad)
                        }
                        
                        Divider()
                        TextField("Unit", text: sensorDataBinding.unit)
                            .autocorrectionDisabled()
                            .textInputAutocapitalization(.never)
                            .frame(width: 50)
                            // New: Disable unit editing for CPU Temp as it's fixed
                            .disabled(sensorDataBinding.type.wrappedValue == "CPU Temp")
                    }
                }
            }
        }
    }
}
