//
//  EditComputerViewOld.swift
//  WOLMonitoring
//
//  Created by Keith Beavers on 9/25/25.
//

// Generated by Google Gemini 2.5 Pro on Thu Sep 25th, 2025 @ 0941

import SwiftUI

struct EditComputerViewOld: View {
    @Binding var computer: Computer
    @Environment(\.dismiss) var dismiss

    @State private var name: String
    @State private var macAddress: String
    
    private var isFormValid: Bool {
        !name.trimmingCharacters(in: .whitespaces).isEmpty &&
        !macAddress.trimmingCharacters(in: .whitespaces).isEmpty
    }

    init(computer: Binding<Computer>) {
        _computer = computer
        _name = State(initialValue: computer.wrappedValue.name ?? "")
        _macAddress = State(initialValue: computer.wrappedValue.macAddress ?? "")
    }

    var body: some View {
        NavigationStack {
            Form {
                TextField("Computer Name", text: $name)
                TextField("MAC Address", text: $macAddress)
                    .autocorrectionDisabled()
                    .textInputAutocapitalization(.never)
            }
            .navigationTitle("Edit Computer")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") {
                        dismiss()
                    }
                }
                ToolbarItem(placement: .confirmationAction) {
                    Button("Save") {
                        computer.name = name
                        computer.macAddress = macAddress
                        dismiss()
                    }
                    .disabled(!isFormValid)
                }
            }
        }
    }
}
